/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 BackGrassT.glb --transform -d 
Files: BackGrassT.glb [5.3MB] > C:\Users\andre\My Stuff\Blender Projects\Minecraft Portfolio\Objects\For Use\BackGrassT-transformed.glb [4.85MB] (9%)
*/

import React from "react";
import { useGLTFWithKTX2 } from "../../utils/useGLTFWithKTX2";
import { convertMaterialsToMeshBasicMaterial } from "../../utils/convertMaterial";

export default function Model(props) {
  const { nodes, materials } = useGLTFWithKTX2(
    "/models/BackGrassT-transformed.glb"
  );
  convertMaterialsToMeshBasicMaterial(materials, 0.5);

  const transparentWaterMaterial = materials["MergedBake_Baked.018"].clone();
  transparentWaterMaterial.transparent = true;
  transparentWaterMaterial.opacity = 0.5;

  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.grass_back_Baked.geometry}
        material={materials["MergedBake_Baked.021"]}
        position={[-6.777, 70.277, -25.075]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.shrubs_Baked.geometry}
        material={materials["MergedBake_Baked.017"]}
        position={[-6.036, 77.158, -55.567]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.water_Baked.geometry}
        material={materials["MergedBake_Baked.018"]}
        position={[-5.297, 60.772, 19.029]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.actual_water_baked.geometry}
        material={transparentWaterMaterial}
        position={[-5.297, 60.772, 19.029]}
        rotation={[Math.PI / 2, 0, 0]}
      />
    </group>
  );
}
