/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ExtrasT.glb --transform -d 
Files: ExtrasT.glb [12.04MB] > C:\Users\andre\My Stuff\Blender Projects\Minecraft Portfolio\Objects\For Use\ExtrasT-transformed.glb [11.95MB] (1%)
*/

import React from "react";

import { useGLTFWithKTX2 } from "../../utils/useGLTFWithKTX2";
import { convertMaterialsToMeshBasicMaterial } from "../../utils/convertMaterial";

export default function Model(props) {
  const { nodes, materials } = useGLTFWithKTX2(
    "/models/ExtrasT-transformed.glb"
  );
  convertMaterialsToMeshBasicMaterial(materials, 0.7);

  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.extras_Baked.geometry}
        material={materials["MergedBake_Baked.019"]}
      />
    </group>
  );
}
