/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ExtrasTwoT.glb --transform -d 
Files: ExtrasTwoT.glb [9.55MB] > C:\Users\andre\My Stuff\Blender Projects\Minecraft Portfolio\Objects\For Use\ExtrasTwoT-transformed.glb [9.46MB] (1%)
*/

import React from "react";

import { useGLTFWithKTX2 } from "../../utils/useGLTFWithKTX2";
import { convertMaterialsToMeshBasicMaterial } from "../../utils/convertMaterial";

export default function Model(props) {
  const { nodes, materials } = useGLTFWithKTX2(
    "/models/ExtrasTwoT-transformed.glb"
  );

  convertMaterialsToMeshBasicMaterial(materials);

  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.extras_two_Baked.geometry}
        material={materials["MergedBake_Baked.020"]}
        position={[-8.228, 64.814, 1.892]}
        rotation={[Math.PI / 2, 0, 0]}
      />
    </group>
  );
}
