/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 FrontGrassT.glb --transform -d 
Files: FrontGrassT.glb [7.39MB] > C:\Users\andre\My Stuff\Blender Projects\Minecraft Portfolio\Objects\For Use\FrontGrassT-transformed.glb [7.3MB] (1%)
*/

import React from "react";

import { useGLTFWithKTX2 } from "../../utils/useGLTFWithKTX2";
import { convertMaterialsToMeshBasicMaterial } from "../../utils/convertMaterial";

export default function Model(props) {
  const { nodes, materials } = useGLTFWithKTX2(
    "/models/FrontGrassT-transformed.glb"
  );
  convertMaterialsToMeshBasicMaterial(materials);
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.grass_center_Baked.geometry}
        material={materials["MergedBake_Baked.004"]}
        position={[-6.777, 70.277, -25.075]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.grass_right_Baked.geometry}
        material={materials["MergedBake_Baked.005"]}
        position={[-6.777, 70.277, -25.075]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.grass_left_Baked.geometry}
        material={materials["MergedBake_Baked.049"]}
        position={[-6.777, 70.277, -25.075]}
        rotation={[Math.PI / 2, 0, 0]}
      />
    </group>
  );
}
