/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 GrassBlocksT.glb --transform -d 
Files: GrassBlocksT.glb [11.35MB] > C:\Users\andre\My Stuff\Blender Projects\Minecraft Portfolio\Objects\For Use\GrassBlocksT-transformed.glb [10.7MB] (6%)
*/

import React from "react";

import { useGLTFWithKTX2 } from "../../utils/useGLTFWithKTX2";
import { convertMaterialsToMeshBasicMaterial } from "../../utils/convertMaterial";

export default function Model(props) {
  const { nodes, materials } = useGLTFWithKTX2(
    "/models/GrassBlocksT-transformed.glb"
  );
  convertMaterialsToMeshBasicMaterial(materials, 0.74);
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.grass_block_first_half_right_Baked.geometry}
        material={materials.MergedBake_Baked}
        position={[5.421, 67.409, -0.825]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.grass_block_first_half_left_Baked.geometry}
        material={materials["MergedBake_Baked.001"]}
        position={[5.421, 67.409, -0.825]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.grass_block_second_half_Baked.geometry}
        material={materials["MergedBake_Baked.002"]}
        position={[5.421, 67.409, -0.825]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.grass_block_third_half_Baked.geometry}
        material={materials["MergedBake_Baked.003"]}
        position={[5.421, 67.409, -0.825]}
        rotation={[Math.PI / 2, 0, 0]}
      />
    </group>
  );
}
