/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 HouseT.glb --transform -d 
Files: HouseT.glb [13.54MB] > C:\Users\andre\My Stuff\Blender Projects\Minecraft Portfolio\Objects\For Use\HouseT-transformed.glb [13.48MB] (1%)
*/

import React from "react";

import { useGLTFWithKTX2 } from "../../utils/useGLTFWithKTX2";
import { convertMaterialsToMeshBasicMaterial } from "../../utils/convertMaterial";

export default function Model(props) {
  const { nodes, materials } = useGLTFWithKTX2(
    "/models/HouseT-transformed.glb"
  );
  convertMaterialsToMeshBasicMaterial(materials);

  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.house_Baked.geometry}
        material={materials["MergedBake_Baked.016"]}
        position={[-4.55, 71.054, 0.595]}
        rotation={[Math.PI / 2, 0, 0]}
      />
    </group>
  );
}
