/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 MobsT.glb --transform -d 
Files: MobsT.glb [698.8KB] > C:\Users\andre\My Stuff\Blender Projects\Minecraft Portfolio\Objects\For Use\MobsT-transformed.glb [506.3KB] (28%)
*/

import React, { useEffect } from "react";

import { useAnimations } from "@react-three/drei";

import { useGLTFWithKTX2 } from "../../utils/useGLTFWithKTX2";
import { convertMaterialsToMeshBasicMaterial } from "../../utils/convertMaterial";

export default function Model({ progress = 0, ...props }) {
  const group = React.useRef();
  const { nodes, materials, animations } = useGLTFWithKTX2(
    "/models/MobsT-transformed.glb"
  );
  convertMaterialsToMeshBasicMaterial(materials);
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    if (actions) {
      Object.values(actions).forEach((action) => {
        action.play();
      });
    }
  }, [actions]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group
          name="Pig_Armature"
          position={[-22.378, 65.49, 3.292]}
          rotation={[-Math.PI, 0, 0]}
        >
          <group
            name="Pig_Body"
            position={[0, -0.025, 0.117]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group
              name="Pig_FLL"
              position={[0.193, 0.439, 0.364]}
              rotation={[Math.PI / 2, 0, 0]}
            >
              <mesh
                name="Pig_FLL_Baked"
                geometry={nodes.Pig_FLL_Baked.geometry}
                material={materials["MergedBake_Baked.105"]}
                position={[-0.201, -0.192, -0.284]}
                rotation={[1.515, 0, 0]}
              />
            </group>
            <group
              name="Pig_BLL"
              position={[0.193, -0.332, 0.364]}
              rotation={[Math.PI / 2, 0, 0]}
            >
              <mesh
                name="Pig_BLL_Baked"
                geometry={nodes.Pig_BLL_Baked.geometry}
                material={materials["MergedBake_Baked.105"]}
                position={[-0.201, -0.116, -1.073]}
                rotation={[1.626, 0, 0]}
              />
            </group>
            <group
              name="Pig_BRL"
              position={[-0.193, -0.332, 0.364]}
              rotation={[Math.PI / 2, 0, 0]}
            >
              <mesh
                name="Pig_BRL_Baked"
                geometry={nodes.Pig_BRL_Baked.geometry}
                material={materials["MergedBake_Baked.105"]}
                position={[0.184, -0.235, -1.054]}
                rotation={[1.515, 0, 0]}
              />
            </group>
            <group
              name="Pig_FRL"
              position={[-0.193, 0.439, 0.364]}
              rotation={[Math.PI / 2, 0, 0]}
            >
              <mesh
                name="Pig_FRL_Baked"
                geometry={nodes.Pig_FRL_Baked.geometry}
                material={materials["MergedBake_Baked.105"]}
                position={[0.184, -0.159, -0.304]}
                rotation={[1.626, 0, 0]}
              />
            </group>
            <group name="Pig_Head" position={[0, 0.601, -0.031]}>
              <mesh
                name="Pig_Head_Baked"
                geometry={nodes.Pig_Head_Baked.geometry}
                material={materials["MergedBake_Baked.105"]}
                position={[-0.008, 0.132, 0.219]}
                rotation={[Math.PI, 0, 0]}
              />
            </group>
            <mesh
              name="Pig_Body_Baked"
              geometry={nodes.Pig_Body_Baked.geometry}
              material={materials["MergedBake_Baked.105"]}
              position={[-0.008, 0.733, 0.188]}
              rotation={[Math.PI, 0, 0]}
            />
          </group>
        </group>
        <group
          name="Pig_Previous_Location"
          position={[-22.378, 65.515, 4.241]}
        />
        <group
          name="Cow_One_Armature"
          position={[16.63, 71.892, -37.602]}
          rotation={[Math.PI / 2, 0, 0]}
        >
          <group name="Cow_One_Body" position={[0, -0.14, 0]}>
            <group
              name="Cow_One_FLL"
              position={[0.259, 0.592, 0.423]}
              rotation={[Math.PI / 2, 0, 0]}
            >
              <mesh
                name="Cow_One_FLL_Baked"
                geometry={nodes.Cow_One_FLL_Baked.geometry}
                material={materials["MergedBake_Baked.105"]}
                position={[0, 0.288, 0]}
                rotation={[Math.PI / 2, 0, 0]}
              />
            </group>
            <group
              name="Cow_One_BLL"
              position={[0.259, -0.314, 0.423]}
              rotation={[Math.PI / 2, 0, 0]}
            >
              <mesh
                name="Cow_One_BLL_Baked"
                geometry={nodes.Cow_One_BLL_Baked.geometry}
                material={materials["MergedBake_Baked.105"]}
                position={[0, 0.288, -0.001]}
                rotation={[Math.PI / 2, 0, 0]}
              />
            </group>
            <group
              name="Cow_One_FRL"
              position={[-0.271, 0.592, 0.423]}
              rotation={[Math.PI / 2, 0, 0]}
            >
              <mesh
                name="Cow_One_FRL_Baked"
                geometry={nodes.Cow_One_FRL_Baked.geometry}
                material={materials["MergedBake_Baked.105"]}
                position={[0.013, 0.288, 0]}
                rotation={[Math.PI / 2, 0, 0]}
              />
            </group>
            <group
              name="Cow_One_BRL"
              position={[-0.271, -0.314, 0.423]}
              rotation={[Math.PI / 2, 0, 0]}
            >
              <mesh
                name="Cow_One_BRL_Baked"
                geometry={nodes.Cow_One_BRL_Baked.geometry}
                material={materials["MergedBake_Baked.105"]}
                position={[0.013, 0.288, -0.001]}
                rotation={[Math.PI / 2, 0, 0]}
              />
            </group>
            <group name="Cow_One_Head" position={[0, 0.749, -0.181]}>
              <mesh
                name="Cow_One_Head_Baked"
                geometry={nodes.Cow_One_Head_Baked.geometry}
                material={materials["MergedBake_Baked.105"]}
                position={[0, 0.166, -0.013]}
                rotation={[Math.PI, 0, 0]}
              />
            </group>
            <mesh
              name="Cow_One_Body_Baked"
              geometry={nodes.Cow_One_Body_Baked.geometry}
              material={materials["MergedBake_Baked.105"]}
              position={[0, 0.14, 0]}
              rotation={[Math.PI, 0, 0]}
            />
          </group>
        </group>
        <group
          name="Cow_Two_Armature"
          position={[-5.005, 67.936, -22.937]}
          rotation={[Math.PI / 2, 0, -1.434]}
        >
          <group name="Cow_Two_Body" position={[0, -0.14, 0]}>
            <group
              name="Cow_Two_FLL"
              position={[0.259, 0.592, 0.423]}
              rotation={[Math.PI / 2, 0, 0]}
            >
              <mesh
                name="Cow_Two_FLL_Baked"
                geometry={nodes.Cow_Two_FLL_Baked.geometry}
                material={materials["MergedBake_Baked.105"]}
                position={[0, 0.288, 0]}
                rotation={[Math.PI / 2, 0, 0]}
              />
            </group>
            <group
              name="Cow_Two_BLL"
              position={[0.259, -0.314, 0.423]}
              rotation={[Math.PI / 2, 0, 0]}
            >
              <mesh
                name="Cow_Two_BLL_Baked"
                geometry={nodes.Cow_Two_BLL_Baked.geometry}
                material={materials["MergedBake_Baked.105"]}
                position={[0, 0.288, -0.001]}
                rotation={[Math.PI / 2, 0, 0]}
              />
            </group>
            <group
              name="Cow_Two_FRL"
              position={[-0.271, 0.592, 0.423]}
              rotation={[Math.PI / 2, 0, 0]}
            >
              <mesh
                name="Cow_Two_FRL_Baked"
                geometry={nodes.Cow_Two_FRL_Baked.geometry}
                material={materials["MergedBake_Baked.105"]}
                position={[0.013, 0.288, 0]}
                rotation={[Math.PI / 2, 0, 0]}
              />
            </group>
            <group
              name="Cow_Two_BRL"
              position={[-0.271, -0.314, 0.423]}
              rotation={[Math.PI / 2, 0, 0]}
            >
              <mesh
                name="Cow_Two_BRL_Baked"
                geometry={nodes.Cow_Two_BRL_Baked.geometry}
                material={materials["MergedBake_Baked.105"]}
                position={[0.013, 0.288, -0.001]}
                rotation={[Math.PI / 2, 0, 0]}
              />
            </group>
            <group name="Cow_Two_Head" position={[0, 0.749, -0.181]}>
              <mesh
                name="Cow_Two_Head_Baked"
                geometry={nodes.Cow_Two_Head_Baked.geometry}
                material={materials["MergedBake_Baked.105"]}
                position={[0, 0.166, -0.013]}
                rotation={[Math.PI, 0, 0]}
              />
            </group>
            <mesh
              name="Cow_Two_Body_Baked"
              geometry={nodes.Cow_Two_Body_Baked.geometry}
              material={materials["MergedBake_Baked.105"]}
              position={[0, 0.14, 0]}
              rotation={[Math.PI, 0, 0]}
            />
          </group>
        </group>
        <group
          name="Villager_Armature"
          position={[1.997, 66.312, -2.928]}
          rotation={[-Math.PI, -0.308, 0]}
        >
          <group name="Villager_Body">
            <group name="Villager_RL" position={[-0.135, 0.842, 0]}>
              <mesh
                name="Villager_RL_Baked"
                geometry={nodes.Villager_RL_Baked.geometry}
                material={materials["MergedBake_Baked.105"]}
                position={[0.05, 0.163, -0.018]}
                rotation={[Math.PI / 2, 0, 0]}
              />
            </group>
            <group name="Villager_LL" position={[0.135, 0.842, 0]}>
              <mesh
                name="Villager_LL_Baked"
                geometry={nodes.Villager_LL_Baked.geometry}
                material={materials["MergedBake_Baked.105"]}
                position={[-0.05, 0.16, 0.018]}
                rotation={[Math.PI / 2, 0, 0]}
              />
            </group>
            <group
              name="Villager_Head"
              position={[0, -0.438, 0.167]}
              rotation={[-Math.PI / 2, 0, 0]}
            >
              <mesh
                name="Villager_Head_Baked"
                geometry={nodes.Villager_Head_Baked.geometry}
                material={materials["MergedBake_Baked.105"]}
                position={[0, 0.162, 0.266]}
                rotation={[Math.PI, 0, 0]}
              />
            </group>
            <mesh
              name="Villager_Body_Baked"
              geometry={nodes.Villager_Body_Baked.geometry}
              material={materials["MergedBake_Baked.105"]}
              position={[0, -0.172, 0.005]}
              rotation={[Math.PI / 2, 0, 0]}
            />
          </group>
        </group>
        <group
          name="Chicken_Armature"
          position={[13.345, 65.19, 7.152]}
          rotation={[0, -0.948, 0]}
        >
          <group
            name="Chicken_Body"
            position={[0, 0.171, -0.02]}
            rotation={[Math.PI / 2, 0, 0]}
          >
            <group
              name="Chicken_RL"
              position={[-0.092, 0.02, 0.216]}
              rotation={[Math.PI / 2, 0, 0]}
            >
              <mesh
                name="Chicken_RL_Baked"
                geometry={nodes.Chicken_RL_Baked.geometry}
                material={materials["MergedBake_Baked.105"]}
                position={[0.036, 0.148, -0.1]}
                rotation={[-Math.PI, 0, 0]}
              />
            </group>
            <group
              name="Chicken_LL"
              position={[0.094, 0.02, 0.216]}
              rotation={[Math.PI / 2, 0, 0]}
            >
              <mesh
                name="Chicken_LL_Baked"
                geometry={nodes.Chicken_LL_Baked.geometry}
                material={materials["MergedBake_Baked.105"]}
                position={[0.052, 0.139, -0.106]}
                rotation={[-Math.PI, 0, 0]}
              />
            </group>
            <group name="Chicken_Head" position={[0, 0.225, -0.16]}>
              <mesh
                name="Chicken_Head_Baked"
                geometry={nodes.Chicken_Head_Baked.geometry}
                material={materials["MergedBake_Baked.105"]}
                position={[0.016, 0.17, -0.02]}
                rotation={[-Math.PI / 2, 0.065, 0]}
              />
            </group>
            <mesh
              name="Chicken_Body_Baked"
              geometry={nodes.Chicken_Body_Baked.geometry}
              material={materials["MergedBake_Baked.105"]}
              position={[0.016, 0.025, 0.05]}
              rotation={[-Math.PI / 2, 0, 0]}
            />
          </group>
        </group>
        <group
          name="Chicken_Previous_Location"
          position={[13.368, 65.338, 6.366]}
          scale={0.335}
        />
      </group>
    </group>
  );
}
